apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-master-pvc
  namespace: dapr-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: openebs-jiva-default

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-cluster-pvc
  namespace: dapr-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: openebs-jiva-default