apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo
spec:
  selector:
    matchLabels:
      app: k8s-demo
  template:
    metadata:
      labels:
        app: k8s-demo
    spec:
      containers:
      - name: k8s-demo
        image: nanwanwang/k8s_demo:v1
        ports:
        - containerPort: 80
        imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-demo
spec:
  selector:
    app: k8s-demo
  type: NodePort
  ports:
  - port: 80
    targetPort: 80


