apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demon-rolebinding
  namespace: kube-system
subjects:
- kind: User
  name: demon
roleRef:
  kind: Role
  name: demon-role
  apiGroup: rbac.authorization.k8s.io #留空字符串也可以,则是用当前的apiGroup
