apiVersion: v1
kind: Pod
metadata:
  name: hook1
  namespace: default
spec:
  containers:
  - name: hook1
    image: nginx
    lifecycle:
      postStart:
        exec:
          command: ["/bin/sh","-c","echo hello from the postStart hook handler > /usr/share/post-start"]

