apiVersion: v1
kind: Pod
metadata:
  name: hook2
  namespace: default
spec:
  volumes:
  - name: message
    hostPath:
      path: /tmp
  containers:
  - name: hook2
    image: busybox
    lifecycle:
      preStop:
        exec: 
          command: ['/bin/sh','-c','echo postsotp > /usr/share/message']
    command: ['/bin/sh','-c',"top"]
    volumeMounts:
    - name: message
      mountPath: /usr/share
    


