apiVersion: v1
kind: Pod
metadata:
  name: liveness-demo1
  namespace: default
spec:
  containers:
  - name: li-rfveness
    image: busybox
    args:
    - /bin/sh
    - -c
    - touch /tmp/healthy;sleep 30;rm -rf /tmp/healthy;sleep 600
    livenessProbe:
      exec: 
        command: ['/bin/sh','-c','cat /tmp/healthy']
      initialDelaySeconds: 5
      periodSeconds: 5
      successThreshold: 1
