apiVersion: v1
kind: Pod
metadata:
  name: resource
  namespace: default
spec:
  containers:
  - name: resource
    image: nginx
    ports:
    - containerPort: 80
    resources:
      limits: 
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 50m
        memory: 50Mi