apiVersion: v1
kind: Pod
metadata:
  name: downwardapi-demo1
  namespace: default
spec:
  containers:
  - name: downwardapi-demo1
    image: busybox
    command: ['/bin/sh','-c','env']
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP

        
    