apiVersion: v1
kind: Pod
metadata:
  name: downwardapi-demo2
  labels:
    k8s-app: test-volume
    node-env: test
  annotations:
    own: demonwang
    build: test
spec:
  volumes:
  - name: podinfo
    downwardAPI:
      items:
      - path: labels
        fieldRef:
          fieldPath: metadata.labels  #来源于 pod的 labels
      - path: annotations
        fieldRef:
          fieldPath: metadata.annotations #来源于pod的 annotations
  containers:
  - name: volume-pod
    image: busybox
    args:
    - sleep
    - "3600"
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo

