apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demon-role
  namespace: kube-system
rules:
- apiGroups: ["","apps"]
  resources: ["deployments","replicasets","pods"]
  verbs: ["get","list","watch","create","update","patch","delete"]

