apiVersion: v1
kind: Pod
metadata:
  name: testcm4-pod
  labels:
    name: testcm4
spec:
  containers:
  - name: testcm4
    image: busybox
    command: ["/bin/sh","-c","cat /etc/config/path/to/mysql.conf"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: myfilecm
        items:
        - key: mysql.conf
          path: path/to/mysql.conf