apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dns01
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: demonwang@hotmail.com
    privateKeySecretRef:
      name: letsencrypt-dns01
    solvers:
    - dns01:   # ACME DNS-01 类型
        webhook:
          groupName: acme.yourcompany.com
          solverName: dnspod
          config:
            region: ""
            accessKeySecretRef:  # 引用 ak
              name: dnspod-secret
              key: access-key
            secretKeySecretRef:  # 引用 sk
              name: dnspod-secret
              key: secret-key