apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: demonwang-com-cert
spec:
  secretName: demonwang-com-tls
  commonName: "*.demonwang.com"
  dnsNames:
  - demonwang.com
  - "*.demonwang.com"
  issuerRef:
    name: cert-manager-webhook-dnspod-cluster-issuer 
    kind: ClusterIssuer