apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: svc-demo
        image: nginx
        ports:
        - name: ng
          containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: svc-demo
spec:
  selector:
    app: myapp
  clusterIP: ""
  ports:
  - targetPort: ng  #不指定 默认跟下面port 一样 也可以在容器里指定containerPort名称 使用名称来指定
    port: 8080
    name: ngport