apiVersion: v1
kind: Pod
metadata:
  name: testcm1-pod
  labels:
    name: testcm1
spec:
  containers:
  - name: testcm1
    image: busybox
    command: ["/bin/sh","-c","env"]
    env:
      - name: DB_HOST
        valueFrom:
          configMapKeyRef:
            name: myliteralcm
            key: db.host
      - name: DB_PORT
        valueFrom:
          configMapKeyRef:
            name: myliteralcm
            key: db.port
    envFrom:
      - configMapRef:
          name: myfilecm