apiVersion: v1
kind: Pod
metadata:
  name: testcm3-pod
spec:
  volumes:
  - name: config-volume
    configMap:
      name: cm-demo1
  containers:
  - name: testcm3
    image: busybox
    command: ["/bin/sh","-c","cat /etc/config/redis.conf"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
