apiVersion: v1
kind: ServiceAccount
metadata:
  name: demon-sa2

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: demon-clusterrole
rules:
- apiGroups: [""]
  resources: ["pods","namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]


---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: demon-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: demon-sa2
  namespace: default
roleRef:
  kind: ClusterRole
  name: demon-clusterrole
  apiGroup: rbac.authorization.k8s.io
