apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: demon-role
  namespace: kube-system
rules:
- apiGroups: [""]
  resources: ["pods","services"]
  verbs: ["get","list"]
- apiGroups: ["apps"]
  resources: ["deployments","replicasets"]  # 可以进行所有的操作 使用*匹配
  verbs: ["*"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: demon-rolebinding
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: demon-role
subjects:
- kind: User   #类型 User Group  ServiceAccount    
  name: demon