apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name:  cron-demo
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    metadata:
      name:  cron-job
    spec:
      template:
        metadata:
          name: busybox
        spec:
          restartPolicy: OnFailure
          containers:
          - name: counter
            image: busybox
            command:
            - /bin/sh
            - "-c"
            - "for i in 9 8 7 6 5 4 3 2 1;do echo $i;done"