apiVersion: v1
kind: Pod
metadata:
  name: opaque-secret-volume2-pod
  labels:
    name: opaque-secret-volume2
spec:
  containers:
  - name: opaque-secret-volume2
    image: busybox
    command: ["/bin/sh","-c","cat /etc/secrets/path/to/user.conf"]
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
  volumes:
  - name: secrets
    secret:
      secretName: opaque-secret
      items:
        - key: username
          path: path/to/user.conf