apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: production
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: echo.demonwang.com
    http:
      paths:
      - path: /
        backend:
          serviceName: production
          servicePort: 80
  tls:
  - hosts:
    - "*.demonwang.com"
    secretName: demonwang-com-tls
