apiVersion: apps/v1
kind: Deployment
metadata:
  name: net5demov2-deployment
spec:
  selector:
    matchLabels:
      app: net5demo-configmapv2
  template:
    metadata:
      labels:
        app: net5demo-configmapv2
    spec:
      containers:
      - name: net5demo-configmapv2
        image: nanwanwang/net5demo:configmapv3
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: net5config
