apiVersion: apps/v1
kind: Deployment
metadata:
  name: net5demo-deployment
spec:
  selector:
    matchLabels:
      app: net5demo-configmap
  template:
    metadata:
      labels:
        app: net5demo-configmap
    spec:
      containers:
      - name: net5demo-configmap
        image: nanwanwang/net5demo:configmap
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 80
        volumeMounts:
          - name: config-volume
            mountPath: /app/appsettings.json
            readOnly: true
            subPath: appsettings.json
      volumes:
      - name: config-volume
        configMap:
          name: net5config
