kind: Service
apiVersion: v1
metadata:
  name:  prometheus
  namespace: kube-monitor
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - name:  http
    port:  9090
    targetPort:  9090
    nodePort: 30007