apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-monitor
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval:     10s 
      evaluation_interval: 15s 
    scrape_configs:
    - job_name: 'prometheus'
      metrics_path: '/metrics'
      static_configs:
      - targets: ['localhost:9090']
    
    - job_name: 'coredns'
      metrics_path: '/metrics'
      static_configs:
      - targets: ['kube-dns.kube-system.svc.cluster.local:9153']
      
    - job_name: 'redis'
      metrics_path: '/metrics'
      scrape_interval:  5s 
      static_configs:
      - targets: ['redis.kube-monitor.svc.cluster.local:9121']
       