apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: kube-monitor
  labels:
    app: prometheus
data:
  prometheus.yml: |
    global:
      scrape_interval:     10s 
      evaluation_interval: 15s 
    scrape_configs:
    - job_name: 'prometheus'
      metrics_path: '/metrics'
      static_configs:
      - targets: ['localhost:9090']
    
    - job_name: 'coredns'
      metrics_path: '/metrics'
      static_configs:
      - targets: ['kube-dns.kube-system.svc.cluster.local:9153']
      
    - job_name: 'redis'
      metrics_path: '/metrics'
      scrape_interval:  5s 
      static_configs:
      - targets: ['redis.kube-monitor.svc.cluster.local:9121']
    
    - job_name: 'nodes'
      kubernetes_sd_configs:     
      - role: node
      relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):10250'
        replacement: '${1}:9100'
        target_label: __address__
        action: replace
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)

    - job_name: 'kubelet'
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      
    - job_name: 'cadvisor'
      kubernetes_sd_configs:
      - role: node
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
        replacement: $1
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        replacement: /metrics/cadvisor
        target_label: __metrics_path__
    - job_name: 'apiserver'
      kubernetes_sd_configs
      - role: endpoints
