kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cstor-demo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: openebs-cstor-disk