apiVersion: v1
kind: Pod
metadata:
  name: test-busybox
  labels:
    name: busybox-pod
spec:
  containers:
  - name: test-busybox
    image: busybox
    command:
    - sleep
    - "3600"
    imagePullPolicy: Always
  nodeSelector:
    com: demonwang
