apiVersion: v1
kind: Pod
metadata:
  name: opaque-secret-volume-pod
  labels:
    name: opaque-secret-volume
spec:
  containers:
  - name: opaque-secret-volume
    image: busybox
    command: ["/bin/sh","-c","ls /etc/secrets"]
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
  volumes:
  - name: secrets
    secret:
      secretName: opaque-secret