apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  {{ template "mychart.labels" . }}
data:
  my-key: my-value
  {{- $releasename := .Release.Name }}
  {{- with .Values.favorite }}
  drink: {{ quote .drink  }}
  food: {{ .food | default "rice" | repeat 3 | quote | upper  }}
  release: {{ $releasename }}
  chart: {{ $.Chart.Name }}
  {{- end }}
  {{ if eq .Values.favorite.drink "coffee" }}
  mug: true
  {{- end }}
  pizzaToppings: |-
  {{- range $index,$topping := .Values.pizzaToppings }}
    - {{ $index}} : {{ $topping | title | quote }}
  {{- end }}
  size: |-
    {{- range tuple "small" "medium" "large"}}
    - {{ . | quote}}
    {{- end}}
  {{- range $key,$val := .Values.favorite}}
  {{ $key }} : {{ $val | quote }}
  {{- end}}  
